version: "3"
services:
  database:
    image: postgres
    container_name: "postgres-quarkus-jdbc"
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: quarkusjdbc