name: Build and test all examples

on:
  push:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/quarkus-testing-kotlin.yml'
      - 'quarkus-*/**'
      - '!*.md'
      - '!**/*.md'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/quarkus-testing-kotlin.yml'
      - 'quarkus-*/**'
      - '!*.md'
      - '!**/*.md'
jobs:
  test:
    name: ${{ matrix.working-dir }}
    runs-on: ubuntu-latest
    container: openjdk:11-jdk
    strategy:
      fail-fast: false
      matrix:
        working-dir:
          - 'quarkus-jpa-kotlin'
          - 'quarkus-mongodb-kotlin'
          - 'quarkus-web-kotlin'
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ matrix.working-dir }}
      - name: assemble ${{ matrix.working-dir }}
        run: ./gradlew assemble
        working-directory: ${{ matrix.working-dir }}
      - name: test ${{ matrix.working-dir }}
        run: ./gradlew test
        working-directory: ${{ matrix.working-dir }}
